spring.application.name=userservice
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/fintech_user_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka client configuration - below is the default anyway, here to show how to override it if needed
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# kafka configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=true
